{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sqlalchemy import create_engine\n",
    "from sqlalchemy.orm import Session\n",
    "from test_model import Person"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [],
   "source": [
    "engine = create_engine('sqlite:///test_db',echo=True)\n",
    "session = Session(engine)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2022-06-25 14:44:41,871 INFO sqlalchemy.engine.Engine BEGIN (implicit)\n",
      "2022-06-25 14:44:41,873 INFO sqlalchemy.engine.Engine SELECT person.id AS person_id, person.name AS person_name, person.size AS person_size \n",
      "FROM person\n",
      "2022-06-25 14:44:41,874 INFO sqlalchemy.engine.Engine [generated in 0.00092s] ()\n"
     ]
    }
   ],
   "source": [
    "persons = session.query(Person).all()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "id:1 name:name_a size:10.5\n",
      "id:3 name:c_update size:3.14\n",
      "id:100 name:name_z size:99.9\n"
     ]
    }
   ],
   "source": [
    "for person in persons:\n",
    "    print(f'id:{person.id} name:{person.name} size:{person.size}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [],
   "source": [
    "new_person = Person(id=4,name='from_model',size=100)\n",
    "session.add(new_person)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2022-06-25 14:44:42,101 INFO sqlalchemy.engine.Engine INSERT INTO person (id, name, size) VALUES (?, ?, ?)\n",
      "2022-06-25 14:44:42,102 INFO sqlalchemy.engine.Engine [generated in 0.00179s] (4, 'from_model', 100.0)\n",
      "2022-06-25 14:44:47,116 INFO sqlalchemy.engine.Engine ROLLBACK\n"
     ]
    },
    {
     "ename": "OperationalError",
     "evalue": "(sqlite3.OperationalError) database is locked\n[SQL: INSERT INTO person (id, name, size) VALUES (?, ?, ?)]\n[parameters: (4, 'from_model', 100.0)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mOperationalError\u001b[0m                          Traceback (most recent call last)",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1819\u001b[0m, in \u001b[0;36mConnection._execute_context\u001b[0;34m(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)\u001b[0m\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1817'>1818</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m evt_handled:\n\u001b[0;32m-> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1818'>1819</a>\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdialect\u001b[39m.\u001b[39;49mdo_execute(\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1819'>1820</a>\u001b[0m             cursor, statement, parameters, context\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1820'>1821</a>\u001b[0m         )\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1822'>1823</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_has_events \u001b[39mor\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine\u001b[39m.\u001b[39m_has_events:\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py:732\u001b[0m, in \u001b[0;36mDefaultDialect.do_execute\u001b[0;34m(self, cursor, statement, parameters, context)\u001b[0m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py?line=730'>731</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mdo_execute\u001b[39m(\u001b[39mself\u001b[39m, cursor, statement, parameters, context\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m):\n\u001b[0;32m--> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py?line=731'>732</a>\u001b[0m     cursor\u001b[39m.\u001b[39;49mexecute(statement, parameters)\n",
      "\u001b[0;31mOperationalError\u001b[0m: database is locked",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mOperationalError\u001b[0m                          Traceback (most recent call last)",
      "\u001b[1;32m/home/cre/Python_WebApp/try_sqlalchemy.ipynb Cell 6'\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> <a href='vscode-notebook-cell://wsl%2Bubuntu-20.04/home/cre/Python_WebApp/try_sqlalchemy.ipynb#ch0000005vscode-remote?line=0'>1</a>\u001b[0m session\u001b[39m.\u001b[39;49mcommit()\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py:1451\u001b[0m, in \u001b[0;36mSession.commit\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=1447'>1448</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_autobegin():\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=1448'>1449</a>\u001b[0m         \u001b[39mraise\u001b[39;00m sa_exc\u001b[39m.\u001b[39mInvalidRequestError(\u001b[39m\"\u001b[39m\u001b[39mNo transaction is begun.\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[0;32m-> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=1450'>1451</a>\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_transaction\u001b[39m.\u001b[39;49mcommit(_to_root\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mfuture)\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py:829\u001b[0m, in \u001b[0;36mSessionTransaction.commit\u001b[0;34m(self, _to_root)\u001b[0m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=826'>827</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_assert_active(prepared_ok\u001b[39m=\u001b[39m\u001b[39mTrue\u001b[39;00m)\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=827'>828</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_state \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m PREPARED:\n\u001b[0;32m--> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=828'>829</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_prepare_impl()\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=830'>831</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_parent \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m \u001b[39mor\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mnested:\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=831'>832</a>\u001b[0m     \u001b[39mfor\u001b[39;00m conn, trans, should_commit, autoclose \u001b[39min\u001b[39;00m \u001b[39mset\u001b[39m(\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=832'>833</a>\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_connections\u001b[39m.\u001b[39mvalues()\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=833'>834</a>\u001b[0m     ):\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py:808\u001b[0m, in \u001b[0;36mSessionTransaction._prepare_impl\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=805'>806</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39msession\u001b[39m.\u001b[39m_is_clean():\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=806'>807</a>\u001b[0m         \u001b[39mbreak\u001b[39;00m\n\u001b[0;32m--> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=807'>808</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msession\u001b[39m.\u001b[39;49mflush()\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=808'>809</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=809'>810</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exc\u001b[39m.\u001b[39mFlushError(\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=810'>811</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mOver 100 subsequent flushes have occurred within \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=811'>812</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39msession.commit() - is an after_flush() hook \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=812'>813</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mcreating new objects?\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=813'>814</a>\u001b[0m     )\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py:3383\u001b[0m, in \u001b[0;36mSession.flush\u001b[0;34m(self, objects)\u001b[0m\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=3380'>3381</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=3381'>3382</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_flushing \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n\u001b[0;32m-> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=3382'>3383</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_flush(objects)\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=3383'>3384</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=3384'>3385</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_flushing \u001b[39m=\u001b[39m \u001b[39mFalse\u001b[39;00m\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py:3523\u001b[0m, in \u001b[0;36mSession._flush\u001b[0;34m(self, objects)\u001b[0m\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=3520'>3521</a>\u001b[0m \u001b[39mexcept\u001b[39;00m:\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=3521'>3522</a>\u001b[0m     \u001b[39mwith\u001b[39;00m util\u001b[39m.\u001b[39msafe_reraise():\n\u001b[0;32m-> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=3522'>3523</a>\u001b[0m         transaction\u001b[39m.\u001b[39mrollback(_capture_exception\u001b[39m=\u001b[39m\u001b[39mTrue\u001b[39;00m)\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py:70\u001b[0m, in \u001b[0;36msafe_reraise.__exit__\u001b[0;34m(self, type_, value, traceback)\u001b[0m\n\u001b[1;32m     <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=67'>68</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m  \u001b[39m# remove potential circular references\u001b[39;00m\n\u001b[1;32m     <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=68'>69</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mwarn_only:\n\u001b[0;32m---> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=69'>70</a>\u001b[0m         compat\u001b[39m.\u001b[39;49mraise_(\n\u001b[1;32m     <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=70'>71</a>\u001b[0m             exc_value,\n\u001b[1;32m     <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=71'>72</a>\u001b[0m             with_traceback\u001b[39m=\u001b[39;49mexc_tb,\n\u001b[1;32m     <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=72'>73</a>\u001b[0m         )\n\u001b[1;32m     <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=73'>74</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m     <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=74'>75</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m compat\u001b[39m.\u001b[39mpy3k \u001b[39mand\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info \u001b[39mand\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info[\u001b[39m1\u001b[39m]:\n\u001b[1;32m     <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=75'>76</a>\u001b[0m         \u001b[39m# emulate Py3K's behavior of telling us when an exception\u001b[39;00m\n\u001b[1;32m     <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py?line=76'>77</a>\u001b[0m         \u001b[39m# occurs in an exception handler.\u001b[39;00m\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py:208\u001b[0m, in \u001b[0;36mraise_\u001b[0;34m(***failed resolving arguments***)\u001b[0m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=204'>205</a>\u001b[0m     exception\u001b[39m.\u001b[39m__cause__ \u001b[39m=\u001b[39m replace_context\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=206'>207</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=207'>208</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exception\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=208'>209</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=209'>210</a>\u001b[0m     \u001b[39m# credit to\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=210'>211</a>\u001b[0m     \u001b[39m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=211'>212</a>\u001b[0m     \u001b[39m# as the __traceback__ object creates a cycle\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=212'>213</a>\u001b[0m     \u001b[39mdel\u001b[39;00m exception, replace_context, from_, with_traceback\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py:3483\u001b[0m, in \u001b[0;36mSession._flush\u001b[0;34m(self, objects)\u001b[0m\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=3480'>3481</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_warn_on_events \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=3481'>3482</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m-> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=3482'>3483</a>\u001b[0m     flush_context\u001b[39m.\u001b[39;49mexecute()\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=3483'>3484</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py?line=3484'>3485</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_warn_on_events \u001b[39m=\u001b[39m \u001b[39mFalse\u001b[39;00m\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py:456\u001b[0m, in \u001b[0;36mUOWTransaction.execute\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py?line=453'>454</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py?line=454'>455</a>\u001b[0m     \u001b[39mfor\u001b[39;00m rec \u001b[39min\u001b[39;00m topological\u001b[39m.\u001b[39msort(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdependencies, postsort_actions):\n\u001b[0;32m--> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py?line=455'>456</a>\u001b[0m         rec\u001b[39m.\u001b[39;49mexecute(\u001b[39mself\u001b[39;49m)\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py:630\u001b[0m, in \u001b[0;36mSaveUpdateAll.execute\u001b[0;34m(self, uow)\u001b[0m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py?line=627'>628</a>\u001b[0m \u001b[39m@util\u001b[39m\u001b[39m.\u001b[39mpreload_module(\u001b[39m\"\u001b[39m\u001b[39msqlalchemy.orm.persistence\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py?line=628'>629</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mexecute\u001b[39m(\u001b[39mself\u001b[39m, uow):\n\u001b[0;32m--> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py?line=629'>630</a>\u001b[0m     util\u001b[39m.\u001b[39;49mpreloaded\u001b[39m.\u001b[39;49morm_persistence\u001b[39m.\u001b[39;49msave_obj(\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py?line=630'>631</a>\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mmapper,\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py?line=631'>632</a>\u001b[0m         uow\u001b[39m.\u001b[39;49mstates_for_mapper_hierarchy(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mmapper, \u001b[39mFalse\u001b[39;49;00m, \u001b[39mFalse\u001b[39;49;00m),\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py?line=632'>633</a>\u001b[0m         uow,\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py?line=633'>634</a>\u001b[0m     )\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py:245\u001b[0m, in \u001b[0;36msave_obj\u001b[0;34m(base_mapper, states, uowtransaction, single)\u001b[0m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=232'>233</a>\u001b[0m     update \u001b[39m=\u001b[39m _collect_update_commands(\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=233'>234</a>\u001b[0m         uowtransaction, table, states_to_update\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=234'>235</a>\u001b[0m     )\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=236'>237</a>\u001b[0m     _emit_update_statements(\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=237'>238</a>\u001b[0m         base_mapper,\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=238'>239</a>\u001b[0m         uowtransaction,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=241'>242</a>\u001b[0m         update,\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=242'>243</a>\u001b[0m     )\n\u001b[0;32m--> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=244'>245</a>\u001b[0m     _emit_insert_statements(\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=245'>246</a>\u001b[0m         base_mapper,\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=246'>247</a>\u001b[0m         uowtransaction,\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=247'>248</a>\u001b[0m         mapper,\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=248'>249</a>\u001b[0m         table,\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=249'>250</a>\u001b[0m         insert,\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=250'>251</a>\u001b[0m     )\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=252'>253</a>\u001b[0m _finalize_insert_update_commands(\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=253'>254</a>\u001b[0m     base_mapper,\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=254'>255</a>\u001b[0m     uowtransaction,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=270'>271</a>\u001b[0m     ),\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=271'>272</a>\u001b[0m )\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py:1097\u001b[0m, in \u001b[0;36m_emit_insert_statements\u001b[0;34m(base_mapper, uowtransaction, mapper, table, insert, bookkeeping)\u001b[0m\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=1093'>1094</a>\u001b[0m records \u001b[39m=\u001b[39m \u001b[39mlist\u001b[39m(records)\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=1094'>1095</a>\u001b[0m multiparams \u001b[39m=\u001b[39m [rec[\u001b[39m2\u001b[39m] \u001b[39mfor\u001b[39;00m rec \u001b[39min\u001b[39;00m records]\n\u001b[0;32m-> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=1096'>1097</a>\u001b[0m c \u001b[39m=\u001b[39m connection\u001b[39m.\u001b[39;49m_execute_20(\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=1097'>1098</a>\u001b[0m     statement, multiparams, execution_options\u001b[39m=\u001b[39;49mexecution_options\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=1098'>1099</a>\u001b[0m )\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=1100'>1101</a>\u001b[0m \u001b[39mif\u001b[39;00m bookkeeping:\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=1101'>1102</a>\u001b[0m     \u001b[39mfor\u001b[39;00m (\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=1102'>1103</a>\u001b[0m         (\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=1103'>1104</a>\u001b[0m             state,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=1112'>1113</a>\u001b[0m         last_inserted_params,\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py?line=1113'>1114</a>\u001b[0m     ) \u001b[39min\u001b[39;00m \u001b[39mzip\u001b[39m(records, c\u001b[39m.\u001b[39mcontext\u001b[39m.\u001b[39mcompiled_parameters):\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1631\u001b[0m, in \u001b[0;36mConnection._execute_20\u001b[0;34m(self, statement, parameters, execution_options)\u001b[0m\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1626'>1627</a>\u001b[0m     util\u001b[39m.\u001b[39mraise_(\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1627'>1628</a>\u001b[0m         exc\u001b[39m.\u001b[39mObjectNotExecutableError(statement), replace_context\u001b[39m=\u001b[39merr\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1628'>1629</a>\u001b[0m     )\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1629'>1630</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m-> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1630'>1631</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m meth(\u001b[39mself\u001b[39;49m, args_10style, kwargs_10style, execution_options)\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py:332\u001b[0m, in \u001b[0;36mClauseElement._execute_on_connection\u001b[0;34m(self, connection, multiparams, params, execution_options, _force)\u001b[0m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=327'>328</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_execute_on_connection\u001b[39m(\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=328'>329</a>\u001b[0m     \u001b[39mself\u001b[39m, connection, multiparams, params, execution_options, _force\u001b[39m=\u001b[39m\u001b[39mFalse\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=329'>330</a>\u001b[0m ):\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=330'>331</a>\u001b[0m     \u001b[39mif\u001b[39;00m _force \u001b[39mor\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39msupports_execution:\n\u001b[0;32m--> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=331'>332</a>\u001b[0m         \u001b[39mreturn\u001b[39;00m connection\u001b[39m.\u001b[39;49m_execute_clauseelement(\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=332'>333</a>\u001b[0m             \u001b[39mself\u001b[39;49m, multiparams, params, execution_options\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=333'>334</a>\u001b[0m         )\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=334'>335</a>\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py?line=335'>336</a>\u001b[0m         \u001b[39mraise\u001b[39;00m exc\u001b[39m.\u001b[39mObjectNotExecutableError(\u001b[39mself\u001b[39m)\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1498\u001b[0m, in \u001b[0;36mConnection._execute_clauseelement\u001b[0;34m(self, elem, multiparams, params, execution_options)\u001b[0m\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1485'>1486</a>\u001b[0m compiled_cache \u001b[39m=\u001b[39m execution_options\u001b[39m.\u001b[39mget(\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1486'>1487</a>\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mcompiled_cache\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine\u001b[39m.\u001b[39m_compiled_cache\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1487'>1488</a>\u001b[0m )\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1489'>1490</a>\u001b[0m compiled_sql, extracted_params, cache_hit \u001b[39m=\u001b[39m elem\u001b[39m.\u001b[39m_compile_w_cache(\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1490'>1491</a>\u001b[0m     dialect\u001b[39m=\u001b[39mdialect,\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1491'>1492</a>\u001b[0m     compiled_cache\u001b[39m=\u001b[39mcompiled_cache,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1495'>1496</a>\u001b[0m     linting\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdialect\u001b[39m.\u001b[39mcompiler_linting \u001b[39m|\u001b[39m compiler\u001b[39m.\u001b[39mWARN_LINTING,\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1496'>1497</a>\u001b[0m )\n\u001b[0;32m-> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1497'>1498</a>\u001b[0m ret \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_execute_context(\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1498'>1499</a>\u001b[0m     dialect,\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1499'>1500</a>\u001b[0m     dialect\u001b[39m.\u001b[39;49mexecution_ctx_cls\u001b[39m.\u001b[39;49m_init_compiled,\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1500'>1501</a>\u001b[0m     compiled_sql,\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1501'>1502</a>\u001b[0m     distilled_params,\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1502'>1503</a>\u001b[0m     execution_options,\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1503'>1504</a>\u001b[0m     compiled_sql,\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1504'>1505</a>\u001b[0m     distilled_params,\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1505'>1506</a>\u001b[0m     elem,\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1506'>1507</a>\u001b[0m     extracted_params,\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1507'>1508</a>\u001b[0m     cache_hit\u001b[39m=\u001b[39;49mcache_hit,\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1508'>1509</a>\u001b[0m )\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1509'>1510</a>\u001b[0m \u001b[39mif\u001b[39;00m has_events:\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1510'>1511</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdispatch\u001b[39m.\u001b[39mafter_execute(\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1511'>1512</a>\u001b[0m         \u001b[39mself\u001b[39m,\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1512'>1513</a>\u001b[0m         elem,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1516'>1517</a>\u001b[0m         ret,\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1517'>1518</a>\u001b[0m     )\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1862\u001b[0m, in \u001b[0;36mConnection._execute_context\u001b[0;34m(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)\u001b[0m\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1858'>1859</a>\u001b[0m             branched\u001b[39m.\u001b[39mclose()\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1860'>1861</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mBaseException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m-> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1861'>1862</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_handle_dbapi_exception(\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1862'>1863</a>\u001b[0m         e, statement, parameters, cursor, context\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1863'>1864</a>\u001b[0m     )\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1865'>1866</a>\u001b[0m \u001b[39mreturn\u001b[39;00m result\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:2043\u001b[0m, in \u001b[0;36mConnection._handle_dbapi_exception\u001b[0;34m(self, e, statement, parameters, cursor, context)\u001b[0m\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2040'>2041</a>\u001b[0m     util\u001b[39m.\u001b[39mraise_(newraise, with_traceback\u001b[39m=\u001b[39mexc_info[\u001b[39m2\u001b[39m], from_\u001b[39m=\u001b[39me)\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2041'>2042</a>\u001b[0m \u001b[39melif\u001b[39;00m should_wrap:\n\u001b[0;32m-> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2042'>2043</a>\u001b[0m     util\u001b[39m.\u001b[39;49mraise_(\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2043'>2044</a>\u001b[0m         sqlalchemy_exception, with_traceback\u001b[39m=\u001b[39;49mexc_info[\u001b[39m2\u001b[39;49m], from_\u001b[39m=\u001b[39;49me\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2044'>2045</a>\u001b[0m     )\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2045'>2046</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=2046'>2047</a>\u001b[0m     util\u001b[39m.\u001b[39mraise_(exc_info[\u001b[39m1\u001b[39m], with_traceback\u001b[39m=\u001b[39mexc_info[\u001b[39m2\u001b[39m])\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py:208\u001b[0m, in \u001b[0;36mraise_\u001b[0;34m(***failed resolving arguments***)\u001b[0m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=204'>205</a>\u001b[0m     exception\u001b[39m.\u001b[39m__cause__ \u001b[39m=\u001b[39m replace_context\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=206'>207</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=207'>208</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exception\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=208'>209</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=209'>210</a>\u001b[0m     \u001b[39m# credit to\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=210'>211</a>\u001b[0m     \u001b[39m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=211'>212</a>\u001b[0m     \u001b[39m# as the __traceback__ object creates a cycle\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py?line=212'>213</a>\u001b[0m     \u001b[39mdel\u001b[39;00m exception, replace_context, from_, with_traceback\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1819\u001b[0m, in \u001b[0;36mConnection._execute_context\u001b[0;34m(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)\u001b[0m\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1816'>1817</a>\u001b[0m                 \u001b[39mbreak\u001b[39;00m\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1817'>1818</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m evt_handled:\n\u001b[0;32m-> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1818'>1819</a>\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdialect\u001b[39m.\u001b[39;49mdo_execute(\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1819'>1820</a>\u001b[0m             cursor, statement, parameters, context\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1820'>1821</a>\u001b[0m         )\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1822'>1823</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_has_events \u001b[39mor\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine\u001b[39m.\u001b[39m_has_events:\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1823'>1824</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdispatch\u001b[39m.\u001b[39mafter_cursor_execute(\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1824'>1825</a>\u001b[0m         \u001b[39mself\u001b[39m,\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1825'>1826</a>\u001b[0m         cursor,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1829'>1830</a>\u001b[0m         context\u001b[39m.\u001b[39mexecutemany,\n\u001b[1;32m   <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py?line=1830'>1831</a>\u001b[0m     )\n",
      "File \u001b[0;32m~/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py:732\u001b[0m, in \u001b[0;36mDefaultDialect.do_execute\u001b[0;34m(self, cursor, statement, parameters, context)\u001b[0m\n\u001b[1;32m    <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py?line=730'>731</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mdo_execute\u001b[39m(\u001b[39mself\u001b[39m, cursor, statement, parameters, context\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m):\n\u001b[0;32m--> <a href='file:///home/cre/Python_WebApp/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py?line=731'>732</a>\u001b[0m     cursor\u001b[39m.\u001b[39;49mexecute(statement, parameters)\n",
      "\u001b[0;31mOperationalError\u001b[0m: (sqlite3.OperationalError) database is locked\n[SQL: INSERT INTO person (id, name, size) VALUES (?, ?, ?)]\n[parameters: (4, 'from_model', 100.0)]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)"
     ]
    }
   ],
   "source": [
    "session.commit()"
   ]
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "50f924bc883a09db1276cb08c605c91ac67fdd49531ef706b81b28bb3d8c9cb0"
  },
  "kernelspec": {
   "display_name": "Python 3.8.10 ('venv': venv)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
